import { randomUUID } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { localLlmConfig, REPO_ROOT } from "./config.js";
import { createLocalLLMProvider } from "./provider.js";
import { collectProjectNotes, createProposal, resolveVaultPath, sha256, validateVaultWritePath } from "./vault.js";
import { ORBIT_OUTPUT_SCHEMA, parseStructuredOutput, validateStructuredOutput } from "./structured-output.js";
import { formatFrontmatter } from "./markdown.js";
import { recordLlmRun, recordVaultProposal } from "./supabase.js";

export function localLlmOutputSchemaExample() {
  return {
    answer: "Human-readable response",
    sources: [{ path: "07 Orbit App/Roadmap/Orbit Axis Roadmap.md", title: "Orbit Axis Roadmap" }],
    proposed_vault_changes: [],
    warnings: [],
    confidence: 0.8,
  };
}

export async function generateProjectAnswer({ prompt, query = "", retrievalQueries = [], propose = null, allowFallback = true } = {}) {
  const config = localLlmConfig();
  const provider = createLocalLLMProvider(config);
  const sources = retrieveSources({ config, prompt, query, retrievalQueries });
  const system = readFileSync(join(REPO_ROOT, "prompts", "local-llm", "orbit-project-assistant.md"), "utf8");
  const expectedChange = propose ? prepareExpectedChange(propose, config.vaultPath) : null;
  const userPrompt = buildUserPrompt({ prompt, sources, expectedChange, config });
  const started = Date.now();
  const result = await provider.generate({
    system,
    prompt: userPrompt,
    format: ORBIT_OUTPUT_SCHEMA,
    contextLength: config.contextLength,
    temperature: config.temperature,
    timeoutMs: config.timeoutMs,
  });

  const parsedResult = result.ok ? parseStructuredOutput(result.text) : { value: null, extracted: false, errors: [result.message || result.status || "generation failed"] };
  const schemaValidation = parsedResult.value
    ? validateStructuredOutput(parsedResult.value, { allowedSources: sources, expectedChange })
    : { ok: false, errors: parsedResult.errors };
  if (!sources.length) schemaValidation.errors.push("no approved vault sources were retrieved");
  schemaValidation.ok = schemaValidation.errors.length === 0;

  let proposal = null;
  let proposalError = null;
  if (result.ok && schemaValidation.ok && expectedChange) {
    try {
      const change = parsedResult.value.proposed_vault_changes[0];
      proposal = createProposal({
        operation: change.operation,
        path: change.path,
        reason: change.reason,
        content: change.content,
        model: result.model,
        promptVersion: config.promptVersion,
        generationDurationMs: result.duration_ms,
        sources: parsedResult.value.sources,
        vaultPath: config.vaultPath,
      });
      await recordVaultProposal(proposal);
    } catch (error) {
      proposalError = error;
      schemaValidation.ok = false;
      schemaValidation.errors.push(...(error.validationErrors || [error.message]));
    }
  }

  const genuineSuccess = result.ok && schemaValidation.ok && (!expectedChange || proposal);
  const fallbackActive = !genuineSuccess && allowFallback && !expectedChange;
  const response = genuineSuccess
    ? parsedResult.value
    : fallbackActive
      ? deterministicAnswer(prompt, sources, schemaValidation.errors)
      : null;
  const status = genuineSuccess ? "ok" : fallbackActive ? "fallback" : "failed";
  const runRecord = await recordLlmRun({
    provider: "ollama",
    model: result.model || config.model || null,
    task_type: expectedChange ? "vault_proposal" : "project_answer",
    prompt_hash: sha256(prompt || ""),
    context_note_ids: sources.map((source) => source.id).filter(Boolean),
    source_paths: sources.map((source) => source.path),
    status,
    duration_ms: result.duration_ms || Date.now() - started,
    input_token_estimate: result.input_tokens || Math.ceil(userPrompt.length / 4),
    output_token_estimate: result.output_tokens || Math.ceil(String(result.text || "").length / 4),
    error_code: genuineSuccess ? null : proposalError ? "proposal_validation_failed" : result.ok ? "structured_output_invalid" : result.status,
    error_metadata: genuineSuccess ? {} : { validation_errors: schemaValidation.errors.slice(0, 20) },
    fallback_used: fallbackActive,
    prompt_version: config.promptVersion,
  });

  return {
    ok: genuineSuccess || fallbackActive,
    provider: "ollama",
    model: result.model || config.model || null,
    used_fallback: fallbackActive,
    generation_label: fallbackActive
      ? "Generated by deterministic fallback"
      : genuineSuccess
        ? `Generated by ${result.model} through local Ollama`
        : "Local Ollama generation failed validation",
    response,
    sources,
    proposal,
    validation: {
      ok: schemaValidation.ok,
      errors: schemaValidation.errors,
      json_extracted_from_markdown: parsedResult.extracted,
    },
    duration_ms: result.duration_ms || Date.now() - started,
    context_length: config.contextLength,
    prompt_version: config.promptVersion,
    raw_status: result.status,
    supabase_run: runRecord,
  };
}

function retrieveSources({ config, prompt, query, retrievalQueries }) {
  const queries = retrievalQueries.length ? retrievalQueries : [query || prompt || "Orbit Axis"];
  const unique = new Map();
  const maxContextChars = Math.max(4000, (config.contextLength - config.maxOutputTokens - 1200) * 4);
  for (const item of queries) {
    for (const source of collectProjectNotes({ vaultPath: config.vaultPath, query: item, limit: 2, maxContextChars })) {
      if (!unique.has(source.path)) unique.set(source.path, source);
    }
  }
  const selected = [];
  let used = 0;
  for (const source of unique.values()) {
    const size = JSON.stringify(source).length;
    if (selected.length && used + size > maxContextChars) continue;
    selected.push(source);
    used += size;
    if (selected.length >= 4) break;
  }
  return selected;
}

function prepareExpectedChange(propose, vaultPath) {
  const operation = String(propose.operation || "create").toLowerCase();
  if (!["create", "update", "append"].includes(operation)) throw new Error(`Unsupported vault operation: ${operation}`);
  const path = validateVaultWritePath(String(propose.path || ""));
  const expected = { operation, path, reason: propose.reason || "" };
  if (operation === "create") {
    expected.requiredId = randomUUID();
    expected.timestamp = new Date().toISOString();
    expected.title = propose.title;
    expected.type = propose.type || "app_update";
    expected.tags = propose.tags || ["orbit", "local-llm"];
    expected.frontmatterTemplate = formatFrontmatter({
      id: expected.requiredId,
      title: expected.title,
      type: expected.type,
      status: "draft",
      created_at: expected.timestamp,
      updated_at: expected.timestamp,
      author: "local_llm",
      source: "orbit",
      llm_managed: true,
      supabase_sync: "metadata",
      related_project: "orbit-axis",
      version: 1,
      tags: expected.tags,
    }).trimEnd();
  } else {
    const { absolute } = resolveVaultPath(vaultPath, path);
    if (!existsSync(absolute)) throw new Error(`Cannot edit missing vault note: ${path}`);
    expected.currentContent = readFileSync(absolute, "utf8");
  }
  return expected;
}

function buildUserPrompt({ prompt, sources, expectedChange, config }) {
  const lines = [
    `Prompt version: ${config.promptVersion}`,
    `Context window configured: ${config.contextLength} tokens`,
    "Use only this supplied project context:",
    JSON.stringify(sources.map(({ path, title, type, headings, excerpt }) => ({ path, title, type, headings, excerpt })), null, 2),
    "",
    "User request:",
    prompt || "Summarize the current Orbit project context.",
  ];
  if (expectedChange) {
    lines.push("", "Return exactly one proposed_vault_changes item matching this request:", JSON.stringify(expectedChange, null, 2));
    if (expectedChange.operation === "create") {
      lines.push("The content must be complete Markdown and MUST begin with frontmatterTemplate exactly as supplied, followed by a blank line and the requested Markdown body. Do not omit or wrap the frontmatter.");
    } else {
      lines.push("The content must be the complete updated Markdown note. Preserve id and created_at, increment version by exactly one, update updated_at to a current ISO timestamp, and change only the requested section.");
    }
  } else {
    lines.push("", "Do not propose any vault changes. proposed_vault_changes must be an empty array.");
  }
  lines.push("", "Return only JSON matching this exact schema. Cite only paths present in the supplied context.", JSON.stringify(ORBIT_OUTPUT_SCHEMA, null, 2));
  return lines.join("\n");
}

function deterministicAnswer(prompt, sources, errors) {
  return {
    answer: `Deterministic retrieval was used because local Ollama generation failed validation. Retrieved ${sources.length} approved project source(s).${prompt ? ` Request: ${prompt}` : ""}`,
    sources: sources.map(({ path, title }) => ({ path, title })),
    proposed_vault_changes: [],
    warnings: errors,
    confidence: sources.length ? 0.55 : 0.2,
  };
}
